### ISSUE TITLE
Permission issues despite all files in plugins being owned by user?

### ISSUE THREAD

**Issue by badmark** [LinuxBeaver/LinuxBeaver#1]
After copying over the GEGL binaries, I receive a permissions error opening Gimp. Removing the files works, as well as running Gimp with Sudo, but Gimp by itself report this error:

```
(gimp:2488320): Json-CRITICAL **: 10:30:49.094: json_node_dup_object: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_OBJECT' failed
**
ERROR:../gegl/operations/core/json.c:558:json_op_register_type_for_file: assertion failed: (root)
Bail out! ERROR:../gegl/operations/core/json.c:558:json_op_register_type_for_file: assertion failed: (root)
Segmentation fault (core dumped)

```

**Comment by LinuxBeaver** [comment]
Maybe you typed a command at the beginning that made your system think all files were owned by root. Check to see who the owner of the file is. It should be your username.

**Comment by badmark** [comment]
I checked file permissions before filing this. If I remove the files, Gimp opens, if I place the files back, they will only open using sudo. All files are owned by the running user.

![image](https://user-images.githubusercontent.com/7435884/218152413-cac0d8f6-85f2-4112-8a3f-068e9ea3e2d2.png)

**Comment by LinuxBeaver** [comment]
Maybe the GEGL Plugins folder has a root version and a local version and you put it in the root directory. Though I am not sure what is going on here.

**Comment by liamquin** [comment]
I'm not sure why you are saying it's a permissions error, although i do not that gegleffects.so is not executable, so you could try, chmod 755 gegleffects.so

Is this GEGL 0.4? Which GIMP version?

**Comment by badmark** [comment]
This is in  ~/.local/share/gegl-0.4

That didn't help:
![image](https://user-images.githubusercontent.com/7435884/218186791-1159811a-8765-4653-acc9-2bdee7385144.png)

Gimp version: 2.10.32

**Comment by liamquin** [comment]
Hmm, i'd suggest trying to remove half of the plug-in files; if that fails, remove half of the ones you have left until it works, then add a few back at a time. It might be you need to recompile one or more of them on your system.

**Comment by badmark** [comment]
Will try this and report back. Thanks!

**Comment by LinuxBeaver** [comment]
Mark every file as non executable and see what happens.

**Comment by LinuxBeaver** [comment]
The problem is the text file. Remove readme.txt and it should work

**Comment by LinuxBeaver** [comment]
Based on the evidence. It was the readme.txt file. The executable permissions are trivial.

**Comment by badmark** [comment]
I still had the issue after deleting readme.txt, it started working when I removed executable permission from the files in the directory.

**Comment by LinuxBeaver** [comment]
odd.  I guess maybe your right. On my machine it doesn't care if it is executable or not.
