### ISSUE TITLE
Menu is too long, I cannot click on "validate"

### ISSUE THREAD

**Issue by BarbzYHOOL** [LinuxBeaver/LinuxBeaver#3]
Hello,

Menus are too long, I cannot click

![image](https://user-images.githubusercontent.com/29780637/224444913-8242b1ba-97bb-413e-b8c5-56c3c3d97057.png)

What can I do? I remember I used to have a plugin for this but it probably no longer works

**Comment by LinuxBeaver** [comment]
On my Linux setup the super key moves Windows. You can manually drag the slider down as an alternative. 

Look into alt or  super key as a way to drag windows.

**Comment by BarbzYHOOL** [comment]
I don't know why but I cannot reproduce the issue, that's weird

I couldn't drag it down most likely.
