### ISSUE TITLE
How to know which filter does what from the GEGL ACTIONS window?

### ISSUE THREAD

**Issue by BarbzYHOOL** [LinuxBeaver/LinuxBeaver#4]
It's very hard to know what you're looking for in the menu, is there a list or something to help me find what I want and can do?

**Comment by LinuxBeaver** [comment]
Each GitHub Page list what each GEGL Filter does and it also has releases. I recommend you go through each Github page and only download releases of GEGL Filters you plan on using - as opposed to the everything in one place download on my main page.

Example if you want to learn about Glossy Balloon
https://github.com/LinuxBeaver/GEGL-glossy-balloon-text-styling/

Some filters even have PDF Guides on their Github pages.

**Comment by BarbzYHOOL** [comment]
When I'm making something artistic, I don't know what I want to do exactly
I can't remember every filter alongside with every gmic effect etc :D 

anyway, i guess that's life
